model_list:
  - model_name: llama-3.3-70b-versatile
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY
  - model_name: llama-3.1-8b-instant
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: os.environ/GROQ_API_KEY

router_settings:
  routing_strategy: simple-shuffle
  allow_fallbacks: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
